### ISSUE TITLE
InvoiceDataTemplate_XSLT_FO.xslt nem helyes Apache FOP szerint (Java)

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice-XSLT#4]
Hello!

InvoiceDataTemplate_XSLT_FO.xslt betöltésnél Apache FOP hibára fut:
"file:/...../InvoiceDataTemplate_XSLT_FO.xslt: line 9295: An attribute whose value must be a QName or whitespace-separated list of QNames had the value '#current'"

Caused by: javax.xml.transform.TransformerConfigurationException: file:/...../InvoiceDataTemplate_XSLT_FO.xslt: line 9295: An attribute whose value must be a QName or whitespace-separated list of QNames had the value '#current'
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:990)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:761)

**Comment by NTCA-developer** [comment]
Szia!

Emlékeim szerint akkor láttam ezt a hibát, amikor nem támogatta a 2.0-át az XSLT parser. A template biztosan valid. Most próbálod használni először, vagy ment már korábban és csak a mostani verziónál jön nálad ez a hiba?

**Comment by EPluribusUnum** [comment]
@NTCA-developer , most próbáltam először. Utánajárok ennek. Köszönöm.

**Comment by NTCA-developer** [comment]
Direktben nem megy Apache-val a PDF, a 2.0-át nem eszi meg. Mi is Saxont használunk előtétnek hogy legyártsa az FO fájlt. Abból már megy FOP-val a PDF. A readme-ben láthatsz példát erre, de segítek is szívesen ha tudok.

**Comment by EPluribusUnum** [comment]
@NTCA-developer , Saxon segített, köszönöm.
